/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMoviequotesMovieQuoteCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API
// Classes:
//   GTLMoviequotesMovieQuoteCollection (0 custom class methods, 2 custom properties)

#import "GTLMoviequotesMovieQuoteCollection.h"

#import "GTLMoviequotesMovieQuote.h"

// ----------------------------------------------------------------------------
//
//   GTLMoviequotesMovieQuoteCollection
//

@implementation GTLMoviequotesMovieQuoteCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLMoviequotesMovieQuote class]
                                forKey:@"items"];
  return map;
}

@end
