/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMoviequotesMovieQuote.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API
// Classes:
//   GTLMoviequotesMovieQuote (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMoviequotesMovieQuote
//

@interface GTLMoviequotesMovieQuote : GTLObject
@property (copy) NSString *entityKey;
@property (copy) NSString *lastTouchDateTime;
@property (copy) NSString *movie;
@property (copy) NSString *quote;
@end
