/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMoviequotes.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API

#import "GTLMoviequotesConstants.h"

#import "GTLMoviequotesMovieQuote.h"
#import "GTLMoviequotesMovieQuoteCollection.h"

#import "GTLQueryMoviequotes.h"
#import "GTLServiceMoviequotes.h"
