/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryMoviequotes.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   moviequotes/v1
// Description:
//   Movie Quotes API
// Classes:
//   GTLQueryMoviequotes (3 custom class methods, 5 custom properties)

#import "GTLQueryMoviequotes.h"

#import "GTLMoviequotesMovieQuote.h"
#import "GTLMoviequotesMovieQuoteCollection.h"

@implementation GTLQueryMoviequotes

@dynamic entityKey, fields, limit, order, pageToken;

#pragma mark -
#pragma mark "moviequote" methods
// These create a GTLQueryMoviequotes object.

+ (id)queryForMoviequoteDeleteWithEntityKey:(NSString *)entityKey {
  NSString *methodName = @"moviequotes.moviequote.delete";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.entityKey = entityKey;
  query.expectedObjectClass = [GTLMoviequotesMovieQuote class];
  return query;
}

+ (id)queryForMoviequoteInsertWithObject:(GTLMoviequotesMovieQuote *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"moviequotes.moviequote.insert";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMoviequotesMovieQuote class];
  return query;
}

+ (id)queryForMoviequoteList {
  NSString *methodName = @"moviequotes.moviequote.list";
  GTLQueryMoviequotes *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLMoviequotesMovieQuoteCollection class];
  return query;
}

@end
